import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {
  ClerkLoaded,
  ClerkLoading,
  ClerkProvider,
  UserButton,
  currentUser,
} from '@clerk/nextjs'
import './globals.css'
import { cn } from '@/lib/utils'
import Link from 'next/link'
import Search from '@/components/search'
import { Skeleton } from '@/components/ui/skeleton'
import { Button } from '@/components/ui/button'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: '⚡OneZap',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const user = await currentUser()

  return (
    <html lang='en'>
      <ClerkProvider>
        <body
          className={cn(
            inter.className,
            'max-w-6xl mx-auto min-h-screen relative'
          )}
        >
          <header className='sticky z-50 top-0 inset-x-0 flex items-center justify-between px-5 py-6 border-b border-black/5 bg-white'>
            <Link href='/' className='text-2xl font-extralight'>
              ⚡<span className='italic'>One</span>Zap
            </Link>

            <nav>
              <ul className='flex items-center justify-between space-x-4'>
                {user ? (
                  <>
                    <li>
                      <Search />
                    </li>
                    <li className='w-8 h-8'>
                      <ClerkLoading>
                        <Skeleton className='w-full h-full rounded-full' />
                      </ClerkLoading>
                      <ClerkLoaded>
                        <UserButton afterSignOutUrl='/' />
                      </ClerkLoaded>
                    </li>
                  </>
                ) : (
                  <>
                    <li>
                      <Button asChild>
                        <Link href='/sign-in'>Sign in</Link>
                      </Button>
                    </li>
                    <li>
                      <Button asChild variant='ghost'>
                        <Link href='/sign-up'>Sign up</Link>
                      </Button>
                    </li>
                  </>
                )}
              </ul>
            </nav>
          </header>
          {children}
        </body>
      </ClerkProvider>
    </html>
  )
}
